feat: post-skeleton
ost-cas-fee-adv-23-24/nextjs-app-team-batman pull request #10
Opened 2024-02-16 12:57 UTC by risuiar2023

> Post Skeleton added

2024-02-17 22:45 UTC, onivue requested changes

2024-02-17 22:45 UTC, onivue commented on components/mumble/mumble-post-skeleton.tsx
> +}
das Skeleton gefällt mir sehr, die grösse usw. ist super.  
Nur die Animation ist nicht fliessend. Das liegt daran, dass gardient nicht so einfach zu animieren ist.   
Leider weiss ich da selber nicht wie man das am besten macht.  

Ich empfehle aber das ganze nicht so komplizier zu machen sondern einfach den animate-pulse von Tailwind zu verwenden, das reicht völlig aus.  
Beispiel: 

```tsx
export default function PostSkeleton() {
  return (
    <div className="relative h-fit w-full items-center rounded-m bg-white px-xl py-l">
      <div className="absolute left-[-30px] top-m grid h-[60px] w-[60px]  rounded-full border-[6px] border-base-100 bg-base-100">
        <div className="animate-pulse rounded-full bg-base-200">&nbsp;</div>
      </div>
      <div className="pb-m">
        <div className="mb-m w-4/12 animate-pulse rounded-s bg-base-200 pb-m">&nbsp;</div>
        <div className="">
          <div className="mb-s w-full animate-pulse rounded-s bg-base-200">&nbsp;</div>
          <div className="mb-m w-10/12  animate-pulse rounded-s bg-base-200">&nbsp;</div>
          <div className="w-7/12 animate-pulse  rounded-s bg-base-200">&nbsp;</div>
        </div>
      </div>
    </div>
  );
}

2024-02-17 22:45 UTC, onivue commented on components/mumble/mumble-post-skeleton.tsx
> +export default function PostSkeleton() {
Ich würde hier noch eine Prop einfügen, damit man mehrere Poss anzeigen kann.
Bspw. wäre es schöner gleich 5-10 skeletions anzuzeigen, damit die Seite voller aussieht.

2024-02-17 22:45 UTC, onivue commented on utils/avatar-fallback.ts
> +export const AVATAR_SKELETON = '/skeleton-avatar.png';
kann gelöscht werden oder?

2024-02-17 22:45 UTC, onivue commented on tailwind.config.ts
> +      },
falls du doch `animate-pulse` verwenden willst, kannst du das enfernen

2024-02-18 07:44 UTC, risuiar2023 commented on components/mumble/mumble-post-skeleton.tsx
> +export default function PostSkeleton() {
Das ist eine coole idee

2024-02-18 09:21 UTC, onivue approved these changes

2024-02-18 09:21 UTC, merged