feat: modal-settings
ost-cas-fee-adv-23-24/nextjs-app-team-batman pull request #17
Opened 2024-02-23 12:03 UTC by risuiar2023

2024-02-27 11:37 UTC, onivue approved these changes
top 👍

2024-03-01 15:56 UTC, onivue requested changes

2024-03-01 15:56 UTC, onivue commented on components/mumble/mumble-post.tsx
> +
hey @risuiar2023 nimm die DisplayName Änderungen weg, ich hab da ein wenig aufgeräumt und eine temporäre lösung gebaut, das Problem ist mit dem `async` dass es nicht als Client Component verwendet werden kann, bspw. als child im infinity scroll...   
Ist sehr kompliziert und das Hauptproblem sind die Daten die von der API kommen.    
Am besten ist wahrscheinlich, dass wir den Displayname einfach weglassen gem. Dozenten sei das egal

2024-03-01 15:58 UTC, onivue commented on components/mumble/mumble-post.tsx
> +
wir können es so anzeigen:
![image](https://github.com/ost-cas-fee-adv-23-24/nextjs-app-team-batman/assets/73725192/ffe3c9ed-10eb-4dca-af1b-d6853acd9cfc)


bei der Präsentation können wir dann erwähnen warum wir uns dafür entschieden haben und was man besser machen könnte

2024-03-01 16:00 UTC, risuiar2023 commented on components/mumble/mumble-post.tsx
> +
Ahh super, ich kämpfe seit lange damit, und jetzt wenn ich scrolle mit infinity scroll, crash it. Ich war am suchen wieso,  dann ok

2024-03-01 16:01 UTC, risuiar2023 commented on components/mumble/mumble-post.tsx
> +
Ich dachte wir können einfach username mit capital anzeigen

2024-03-01 16:03 UTC, onivue commented on components/mumble/mumble-post.tsx
> +
noch besser 👍  dann passe ich es an auf Username mit Capital

2024-03-01 16:05 UTC, onivue commented on components/mumble/mumble-post.tsx
> +
![image](https://github.com/ost-cas-fee-adv-23-24/nextjs-app-team-batman/assets/73725192/a1585510-1bfa-43d9-9730-5edd36138fd3)

2024-03-01 16:06 UTC, risuiar2023 commented on components/mumble/mumble-post.tsx
> +
ja, einfach in mumble-user-info 
![image](https://github.com/ost-cas-fee-adv-23-24/nextjs-app-team-batman/assets/145476582/1ecb37ca-0e84-4fbf-97b5-c58f81b6d02b)

2024-03-03 08:28 UTC, onivue approved these changes
top, gibt noch probleme mit API aber das schauen wir mit den Dozenten an

2024-03-03 08:29 UTC, merged